name: Build phpBB Swedish Language Pack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read versions
        id: version
        run: |
          source VERSION

          echo "phpbb_version=$phpbb_version" >> $GITHUB_OUTPUT
          echo "language_version=$language_version" >> $GITHUB_OUTPUT

      - name: Create package structure
        run: |
          mkdir -p svenska_${{ steps.version.outputs.phpbb_version }}/swedish_${{ steps.version.outputs.phpbb_version }}
          cp -r phpBB/* svenska_${{ steps.version.outputs.phpbb_version }}/swedish_${{ steps.version.outputs.phpbb_version }}/

      - name: Create ZIP
        run: |
          zip -r phpBB-${{ steps.version.outputs.phpbb_version }}-sv-${{ steps.version.outputs.language_version }}.zip svenska_${{ steps.version.outputs.phpbb_version }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: phpBB-${{ steps.version.outputs.phpbb_version }}-sv-${{ steps.version.outputs.language_version }}
          name: phpBB-${{ steps.version.outputs.phpbb_version }} Swedish Language Pack ${{ steps.version.outputs.language_version }}
          files: |
            svenska_${{ steps.version.outputs.version }}.zip
